"""Game rounds served exclusively from the frozen TEST manifest.

Train images never reach the game — the manifest is generated by
`python -m ml.dataset` from the official test split only. The truth label
stays server-side until /reveal so browser devtools can't spoil a round.
"""

import json
import uuid
from collections import OrderedDict
from pathlib import Path
from random import Random


class RoundStore:
    MAX_OPEN_ROUNDS = 500

    def __init__(self, data_root: str, manifest_path: str, labels: list, seed: int | None = None):
        self.data_root = Path(data_root)
        self.manifest = json.loads(Path(manifest_path).read_text())
        self.labels = labels
        self._rng = Random(seed)
        self._open: OrderedDict[str, int] = OrderedDict()  # round_id -> manifest index

    def new_round(self) -> dict:
        idx = self._rng.randrange(len(self.manifest))
        round_id = uuid.uuid4().hex
        self._open[round_id] = idx
        while len(self._open) > self.MAX_OPEN_ROUNDS:
            self._open.popitem(last=False)
        return {"round_id": round_id, "image_url": f"/round/{round_id}/image"}

    def image_path(self, round_id: str) -> Path | None:
        idx = self._open.get(round_id)
        if idx is None:
            return None
        return self.data_root / self.manifest[idx]["path"]

    def truth(self, round_id: str) -> dict | None:
        idx = self._open.get(round_id)
        if idx is None:
            return None
        return self.labels[self.manifest[idx]["class_idx"]]
